/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "avgBdayCalc": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "avgBdayCalcAPI": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}